app.js, modules/availability.js, package.json, serverless.yml, yarn.lock
- to be included as /avail [user | section]:[param]
=> [G2M] Availability - Basic Interface of Asana Dev Avail Bot

serverless.yml
Looks good so far. The added expense shouldn't exceed $10 per month.
In the future, to further better the experience, we can make core legion APIs that intercept those slash commands to defer the actual execution to subsequent functions and respond 200 immediately. We should leverage [message interactivity feature](https://api.slack.com/messaging/interactivity) by slack to make this a really good user experience.
=> [G2M] Devops/provisioned concurrency

app.js, modules/availability.js, worker.js
- add support for omitting 'command'
=> [G2M] Availability - Fuzzy Params

serverless.yml
=> [G2M] Fix - Add Avail Worker

modules/availability.js
- have a default case for unassigned tasks
=> [G2M] Avail - Handle Null Assignee

modules/diff.js
answer found in https://stackoverflow.com/a/3824122/158111 (first portion, we're not interested in finding out reverts)
=> [G2M] diff - dedupe merge commits

.github/workflows/deploy-dev.yml, modules/diff.js, serverless.yml
diff - fix netlify siteId for overlord
also delete unused ASANA_TOKEN reference
=> [G2M] diff - fix netlify siteId for overlord

modules/bday.js
- designed slack messages being sent to prompter and receiver with blocks, emojis and gifs for all scenarios: sending card to bday person, sending card to team to sign card and send celebration message in general channel
- can include optional custom message when sending card to bday person OR for sending celebration message in general channel
- for sending card to bday person, includes real name of sender and bday person (for aesthetics)
FYI: When sending out card for signing and prompts sent back to initiator, full names are shown (not user names) - screenshots showing user names
**What Bday person gets with no custom message**
/bday send https://google.com to @maluhoss 
**What Bday person sees with custom message**
/bday send https://google.com to @maluhoss Hope you have an amazing …
=> [G2M] Format Slack Messages with more flair and context

modules/index.js, modules/notes.js
generate meeting notes out of team update in slack. Currently only compiling `did` and `questions`
- from any channel do `/notes template` to get the template bellow
```
Did - Common
- react-labs/chip - improved style and color
Did - Atom
- 
Did - Snoke
- 
Did - Automation
-
Did - Data
-
Doing
-
Questions
-
```
- from any channel do `/notes <link>` where link is the slack message link of the shared template from hugo where ppl add their updates as a thread, inside #dev channel. The notes are returned in slack. Ongoing research to populate hugo directly or improve style. Looks like:
=> [G2M]Meeting notes

modules/notes.js
my mistake, named `Snoke` instead of `Locus`
=> [G2M]notes - adjust project categories

.github/workflows/deploy-dev.yml, app.js, modules/bday-blocks.js, modules/bday-interactive.js, modules/bday.js, modules/index.js, yarn.lock
- send link to each #general member to sign card
- send link to bday user by dm
- announce bday celebration in #general channel
TODO:
=> [G2M] bday - send link to members in #general channel excluding bday user

.npmrc, modules/diff.js, package.json, yarn.lock
- less annoying with the use of attachments (so has native show more/less)
- holds more content (at most show up to 48 commits). when exceeded, additional hint message and link to full diff on github is shown
- naively detects potential breaking changes (commits that contain break/s/ing or incompat/ible/ibility 
- highlights contributors (when more than one)
deployed to `test` stage and in effect
=> [G2M] diff - better control, info, and highlights

.eslintrc.js, google-api/googleapis.js, modules/diff.js, modules/pipeline.js, modules/slack.js, package.json, yarn.lock
on top of #55 
Add scheduled demos from [demo calendar](https://calendar.google.com/calendar/u/0?cid=Y18wZGdoZ3MyNWo3cWplNmFhZmw0NDhybXQxY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t) using google api
if no demos scheduled, there's no message
=> [G2M]Diff/calendar

app.js, google-api/googleapis.js, modules/demo.js, modules/index.js
built on top of #56 
[this should do for an initial request, but can def be improved]
slash command integration to create an event in the `Demo` google Calendar
=> [G2M] /demo command

app.js, google-api/googleapis.js, modules/demo.js
1. `invokeLambda` not properly implemented for `/demo`
2. in `/diff`, when using lambda, events at 9:30am and 2pm become 2:30pm and 7pm respectively. I guess google API is fetching events in the localtime of the caller. In this case, I'm assuming lambda causes it to be UTC - since when testing locally all looks good.
I think adding timezone to the parser should do but I'm not sure how to test
=> [G2M]Patch calendar

modules/notes.js
- to allow data team to utilize `/notes <slack link that includes hugo note>`
- included temp fix for when match is null (messages that come from Hugo for example)
=> [G2M] Notes - make slack message link flexible

modules/diff.js, package.json, yarn.lock
=> [G2M] diff - incorporate @eqworks/release parse commit

modules/bday-interactive.js, modules/bday.js
issue: when sending multi bday cards to be signed at the same time, bday people were excluded and would not get each other's cards. 
now the message is modified so bday person gets the cards from other bday people when issuing multi-sign messages
=> [G2M] Bday sign fix multi-bday logic

.github/workflows/deploy-dev.yml, .github/workflows/main.yml, modules/diff.js, yarn.lock
- [channel context change](https://github.com/EQWorks/legion/pull/73/files#diff-fc82d035a200351dfc0f777f93071a13291a3e1c6d33d9a8496a6efafa0d0bac)
- CI workflow step actions updates
- rename `master` to `main` (with workflow update support)
- routine `yarn upgrade-interactive`
=> [G2M] diff - channel context defautl product, update CI workflows

app.js, package.json, yarn.lock
=> [G2M] devops - add sentry logging for serverless handler, remove deprecated body-parser deps

modules/diff.js, modules/util.js
- context: due to change in handle for slack groups, error happened as seen in [thread](https://eqworks.slack.com/archives/C0152M1B9EZ/p1625589399221600?thread_ts=1625588993.220800&cid=C0152M1B9EZ)
- working on top of https://github.com/EQWorks/legion/pull/73
=> [G2M] Diff - fix error handling

modules/diff.js, modules/products.js, modules/release.js
- context: diff command had error handling fixed but not in other slash commands like release, could not release firstorder
- created separate file for product management
- tested and successfully deployed firstorder to beta stage - [ref](https://eqworks.slack.com/archives/G8UF1B0J1/p1626900631009600)
=> [G2M] Release - fix error handling

.github/workflows/deploy-dev.yml
context [here](https://eqworks.slack.com/archives/CB7557258/p1640184445014200)
Incorporating [release](https://github.com/EQWorks/release) into the deployment workflow in this repo.
=> [G2M] devops - auto generate release notes

package-lock.json, package.json, serverless.yml
this should work now with `legion.eqworks.io/dev` (the only stage we have now is `dev`)
also with `npm upgrade` for some periodic dep upgrade
=> [G2M] devops - apply custom domain legion.eqworks.io/<stage>

.github/workflows/deploy-dev.yml, .github/workflows/main.yml, modules/commands/diff.js, modules/lib/products.js, package-lock.json, package.json, serverless.yml
this allows for predefined product "bundles" to trigger multiple product/project/repo diff and responses:
(commands ^ respectively `/diff notebook`, `/diff atom`, `/diff locus`)
=> [G2M] Diff - product bundle support

modules/commands/paymi.js
depends on https://github.com/EQWorks/paymi-report-jobs/pull/73
=> [G2M] paymi - add type 'weekly' for adhoc weekly ops report

modules/lib/products.js
enable slash command `/diff` and `/release` for snoke-dashboard variants (as `cox-dashboard` and `paymi-dashboard`)
=> [G2M] product - support diff and release of snoke dashboard

modules/commands/paymi.js
depends on https://github.com/EQWorks/paymi-report-jobs/pull/80
`/paymi report mb <start> <end>` where `<start>` and `<end>` are in the form of `YYYY-MM-DD`
=> [G2M] paymi - add type 'mb' for member balances (range) report
